name: Build and Deploy to Infomaniak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Étape 3 : Installer les dépendances
      - name: Install Dependencies
        run: npm ci

      # Étape 4 : Build
      - name: Build Application
        run: npm run build

      # Créer le .env avec le secret GitHub
      - name: Create .env
        run: |
          echo "MAIL_SMTP_HOST=${{ secrets.MAIL_SMTP_HOST }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> .env
          echo "MAIL_KEY=${{ secrets.MAIL_KEY }}" >> .env
          echo ".env file created successfully"

      # Étape 5d : Copier les fichiers racine
      - name: Upload root files (SFTP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ./*
          exclude: "node_modules,build"
          target: ${{ secrets.SERVER_PATH }}
          overwrite: true
          timeout: 120s
          command_timeout: 20m
          protocol: sftp
          debug: true
